import { Networks } from './types/network';

export const networks: Networks = {
  97: {
    name: 'BNB Smart Chain Testnet',
    pionerChainId: 'bnbTest',
    config: 'BSC testnet',
    chain: 'BSC',
    rpc: [
      'https://data-seed-prebsc-1-s1.bnbchain.org:8545',
      'https://data-seed-prebsc-2-s1.bnbchain.org:8545',
      'https://data-seed-prebsc-1-s2.bnbchain.org:8545',
      'https://data-seed-prebsc-2-s2.bnbchain.org:8545',
      'https://data-seed-prebsc-1-s3.bnbchain.org:8545',
      'https://data-seed-prebsc-2-s3.bnbchain.org:8545',
      'https://bsc-testnet-rpc.publicnode.com',
      'wss://bsc-testnet-rpc.publicnode.com',
    ],
    faucets: ['https://testnet.bnbchain.org/faucet-smart'],
    nativeCurrency: {
      name: 'BNB Chain Native Token',
      symbol: 'tBNB',
      decimals: 18,
    },
    infoURL: 'https://www.bnbchain.org/en',
    shortName: 'bnbt',
    chainId: 97,
    networkId: 97,
    slip44: 1,
    explorers: [
      {
        name: 'bscscan-testnet',
        url: 'https://testnet.bscscan.com',
        standard: 'EIP3091',
      },
    ],
    contracts: {
      FakeUSD: '',
      PionerV1: '',
      PionerV1Compliance: '',
      PionerV1Open: '',
      PionerV1Close: '',
      PionerV1Default: '',
      PionerV1View: '',
      PionerV1Oracle: '',
      PionerV1Wrapper: '',
    },
  },
  421614: {
    name: 'Arbitrum Sepolia',
    pionerChainId: 'arbitrumSepoliaTest',
    config: 'Arbitrum Sepolia',
    title: 'Arbitrum Sepolia Rollup Testnet',
    chain: 'ETH',
    rpc: [
      'https://sepolia-rollup.arbitrum.io/rpc',
      'https://arbitrum-sepolia.infura.io/v3/${INFURA_API_KEY}',
    ],
    faucets: [],
    nativeCurrency: {
      name: 'Sepolia Ether',
      symbol: 'ETH',
      decimals: 18,
    },
    infoURL: 'https://arbitrum.io',
    shortName: 'arb-sep',
    chainId: 421614,
    networkId: 421614,
    slip44: 1,
    explorers: [
      {
        name: 'Arbitrum Sepolia Rollup Testnet Explorer',
        url: 'https://sepolia-explorer.arbitrum.io',
        standard: 'EIP3091',
      },
    ],
    parent: {
      type: 'L2',
      chain: 'eip155-11155111',
      bridges: [
        {
          url: 'https://bridge.arbitrum.io',
        },
      ],
    },
    contracts: {
      FakeUSD: '',
      PionerV1: '',
      PionerV1Compliance: '',
      PionerV1Open: '',
      PionerV1Close: '',
      PionerV1Default: '',
      PionerV1View: '',
      PionerV1Oracle: '',
      PionerV1Wrapper: '',
    },
  },
  80001: {
    name: 'Mumbai',
    pionerChainId: 'mumbai',
    config: 'Mumbai',
    title: 'Polygon Testnet Mumbai',
    chain: 'Polygon',
    icon: 'polygon',
    rpc: [
      'https://rpc-mumbai.maticvigil.com',
      'https://polygon-mumbai-bor-rpc.publicnode.com',
      'wss://polygon-mumbai-bor-rpc.publicnode.com',
      'https://polygon-mumbai.gateway.tenderly.co',
      'wss://polygon-mumbai.gateway.tenderly.co',
    ],
    faucets: ['https://faucet.polygon.technology/'],
    nativeCurrency: {
      name: 'MATIC',
      symbol: 'MATIC',
      decimals: 18,
    },
    infoURL: 'https://polygon.technology/',
    shortName: 'maticmum',
    chainId: 80001,
    networkId: 80001,
    slip44: 1,
    explorers: [
      {
        name: 'polygonscan',
        url: 'https://mumbai.polygonscan.com',
        standard: 'EIP3091',
      },
    ],
    contracts: {
      FakeUSD: '',
      PionerV1: '',
      PionerV1Compliance: '',
      PionerV1Open: '',
      PionerV1Close: '',
      PionerV1Default: '',
      PionerV1View: '',
      PionerV1Oracle: '',
      PionerV1Wrapper: '',
    },
  },
  11155420: {
    name: 'OP Sepolia Testnet',
    pionerChainId: 'opSepoliaTest',
    config: 'Optimism Sepolia',
    chain: 'ETH',
    rpc: ['https://sepolia.optimism.io'],
    faucets: ['https://app.optimism.io/faucet'],
    nativeCurrency: {
      name: 'Sepolia Ether',
      symbol: 'ETH',
      decimals: 18,
    },
    infoURL: 'https://optimism.io',
    shortName: 'opsep',
    chainId: 11155420,
    networkId: 11155420,
    slip44: 1,
    explorers: [
      {
        name: 'opscout',
        url: 'https://optimism-sepolia.blockscout.com',
        icon: 'blockscout',
        standard: 'EIP3091',
      },
    ],
    contracts: {
      FakeUSD: '',
      PionerV1: '',
      PionerV1Compliance: '',
      PionerV1Open: '',
      PionerV1Close: '',
      PionerV1Default: '',
      PionerV1View: '',
      PionerV1Oracle: '',
      PionerV1Wrapper: '',
    },
  },
  43113: {
    name: 'Avalanche Fuji Testnet',
    pionerChainId: 'fuji',
    config: 'fuji',
    chain: 'AVAX',
    icon: 'avax',
    rpc: [
      'https://api.avax-test.network/ext/bc/C/rpc',
      'https://avalanche-fuji-c-chain-rpc.publicnode.com',
      'wss://avalanche-fuji-c-chain-rpc.publicnode.com',
    ],
    faucets: ['https://faucet.avax-test.network/'],
    nativeCurrency: {
      name: 'Avalanche',
      symbol: 'AVAX',
      decimals: 18,
    },
    infoURL: 'https://cchain.explorer.avax-test.network',
    shortName: 'Fuji',
    chainId: 43113,
    networkId: 1,
    slip44: 1,
    explorers: [
      {
        name: 'snowtrace',
        url: 'https://testnet.snowtrace.io',
        standard: 'EIP3091',
      },
    ],
    contracts: {
      FakeUSD: '0xF1FBfB0a2Cc4c44253b39542B26716314A34F0B6',
      PionerV1: '0xbfd48b8255FE04615C441EAa7033C145f432A2d0',
      PionerV1Compliance: '0x13DDdc7BfE3bdDCde46249D86C1a23EDd5C3212E',
      PionerV1Open: '0xEf1C0Bc9506BF71A9f489E7f7B559A5DC957362D',
      PionerV1Close: '0xafe3F9845E1023Aa71BE74E9DDCf29402c95Dc25',
      PionerV1Default: '0x4dE711a0aD4e91637F66d0977a79Ce59F0A30B27',
      PionerV1View: '0xB10FFAa9e4facbC3080612b178938431fA7aD9a0',
      PionerV1Oracle: '0x4Eec7C251fc99951B33B8ddB2cB0922f438EF8f2',
      PionerV1Wrapper: '0xD607412293711928C574a5CcF8AF2e1aca0d4543',
    },
  },
  43114: {
    name: 'Avalanche C-Chain',
    pionerChainId: 'avax',
    chain: 'AVAX',
    icon: 'avax',
    rpc: [
      'https://api.avax.network/ext/bc/C/rpc',
      'https://avalanche-c-chain-rpc.publicnode.com',
      'wss://avalanche-c-chain-rpc.publicnode.com',
    ],
    features: [
      {
        name: 'EIP1559',
      },
    ],
    faucets: [],
    nativeCurrency: {
      name: 'Avalanche',
      symbol: 'AVAX',
      decimals: 18,
    },
    infoURL: 'https://www.avax.network/',
    shortName: 'avax',
    chainId: 43114,
    networkId: 43114,
    slip44: 9005,
    explorers: [
      {
        name: 'snowtrace',
        url: 'https://snowtrace.io',
        standard: 'EIP3091',
      },
    ],
    contracts: {
      FakeUSD: '',
      PionerV1: '',
      PionerV1Compliance: '',
      PionerV1Open: '',
      PionerV1Close: '',
      PionerV1Default: '',
      PionerV1View: '',
      PionerV1Oracle: '',
      PionerV1Wrapper: '',
    },
  },
  3441005: {
    name: 'Manta Pacific Testnet',
    pionerChainId: 'mantaTest',
    config: 'Mantle Testnet',
    chain: 'Manta Pacific',
    rpc: ['https://manta-testnet.calderachain.xyz/http'],
    faucets: [],
    nativeCurrency: {
      name: 'Manta',
      symbol: 'MANTA',
      decimals: 18,
    },
    features: [
      {
        name: 'EIP155',
      },
      {
        name: 'EIP1559',
      },
    ],
    infoURL: 'https://manta-testnet.caldera.dev/',
    shortName: 'mantaTestnet',
    chainId: 3441005,
    networkId: 3441005,
    slip44: 1,
    icon: 'manta',
    explorers: [
      {
        name: 'manta-testnet Explorer',
        url: 'https://manta-testnet.calderaexplorer.xyz',
        standard: 'EIP3091',
      },
    ],
    contracts: {
      FakeUSD: '',
      PionerV1: '',
      PionerV1Compliance: '',
      PionerV1Open: '',
      PionerV1Close: '',
      PionerV1Default: '',
      PionerV1View: '',
      PionerV1Oracle: '',
      PionerV1Wrapper: '',
    },
  },
  84532: {
    name: 'Base Sepolia Testnet',
    pionerChainId: 'baseSepoliaTest',
    config: 'Base Sepolia',
    chain: 'ETH',
    rpc: [
      'https://sepolia.base.org',
      'https://base-sepolia-rpc.publicnode.com',
      'wss://base-sepolia-rpc.publicnode.com',
    ],
    faucets: [],
    nativeCurrency: {
      name: 'Sepolia Ether',
      symbol: 'ETH',
      decimals: 18,
    },
    infoURL: 'https://base.org',
    shortName: 'basesep',
    chainId: 84532,
    networkId: 84532,
    slip44: 1,
    icon: 'baseTestnet',
    explorers: [
      {
        name: 'basescout',
        url: 'https://base-sepolia.blockscout.com',
        icon: 'blockscout',
        standard: 'EIP3091',
      },
    ],
    contracts: {
      FakeUSD: '',
      PionerV1: '',
      PionerV1Compliance: '',
      PionerV1Open: '',
      PionerV1Close: '',
      PionerV1Default: '',
      PionerV1View: '',
      PionerV1Oracle: '',
      PionerV1Wrapper: '',
    },
  },
  1442: {
    name: 'Polygon zkEVM Testnet',
    pionerChainId: 'skevmTest',
    config: 'zkEVM Testnet',
    title: 'Polygon zkEVM Testnet',
    chain: 'Polygon',
    rpc: ['https://rpc.public.zkevm-test.net'],
    faucets: [],
    nativeCurrency: {
      name: 'Ether',
      symbol: 'ETH',
      decimals: 18,
    },
    infoURL: 'https://polygon.technology/solutions/polygon-zkevm/',
    shortName: 'testnet-zkEVM-mango',
    chainId: 1442,
    networkId: 1442,
    slip44: 1,
    explorers: [
      {
        name: 'Polygon zkEVM explorer',
        url: 'https://explorer.public.zkevm-test.net',
        standard: 'EIP3091',
      },
    ],
    contracts: {
      FakeUSD: '',
      PionerV1: '',
      PionerV1Compliance: '',
      PionerV1Open: '',
      PionerV1Close: '',
      PionerV1Default: '',
      PionerV1View: '',
      PionerV1Oracle: '',
      PionerV1Wrapper: '',
    },
  },
  64165: {
    name: 'Sonic Testnet',
    pionerChainId: 'sonic',
    rpc: ['https://rpc.sonic.fantom.network/'],
    faucets: ['https://app.optimism.io/faucet'],
    chainId: 64165,
    networkId: 64165,
    contracts: {
      FakeUSD : '0xd7B344b7f9AB370dAef394B738896F4213dDd620',
      PionerV1: '0xfa64BF81f4bf9567f2918CF0a14BdCC4d1967552', 
      PionerV1Compliance: '0xA884E45DD832f700f3623BCcFf0B3A7509aFD943', 
      PionerV1Open: '0x3390F047fd2be35D82BdA76244Fd26E7BD7DCe85', 
      PionerV1Close: '0xa96D664139b07b22B5466c32B54382b832a8670E', 
      PionerV1Default: '0x1Dc62fdCEE2a7fd9c6D04812F405ADB9c970C96e', 
      PionerV1View: ', 0xe156503Ef46d40317eA9Baff7Bb37BE68E912D43', 
      PionerV1Oracle: '0x5a7B850651e46d6D7d6D2DCB813A763E08929ceF', 
      PionerV1Wrapper: '0xcE6C9f404D3f907ab391dDE4B964Be28090a77a3'
    },
  },
  4002: {
    name: 'Ftm Testnet',
    pionerChainId: 'ftmTestnet',
    rpc: ['https://rpc.ankr.com/fantom_testnet/'],
    faucets: ['https://testnet.bnbchain.org/faucet-smart'],
    chainId: 4002,
    networkId: 4002,
    contracts: {
      FakeUSD : '0x5BF256c4caF463BE8fe1e57cAe390B5245079C55',
      PionerV1: '0x33FD7230Faf831C980950EE181A46fCDe73A0FD6', 
      PionerV1Compliance: '0xe6Ade75C62D9Bbb37250B884E4ADbe690D13603D', 
      PionerV1Open: '0xC7C6387221E072dC5cDBA9E3168530Da579bAdeB', 
      PionerV1Close: '0x0314605edB695ca19D19141Ff7F826088E5F935E', 
      PionerV1Default: '0xB81f4582a8a365cFD9Cb16Eb2fb434f3795fa1B4', 
      PionerV1View: '0xEa3348476D2E32F27872Ff9c71ee5F558Df08fB9', 
      PionerV1Oracle: '0x39A921Cf769Fa6763669C71C521253419e32e67f', 
      PionerV1Wrapper: '0x14C5BEb9594cea6BDbdf85F6a85c95B894127a5D'
    },
  }
};
