// config.ts

export const networks = {
  bnbTest: {
    name: 'BNB Smart Chain Testnet',
    pionerChainId: 'bnbTest',
    config: 'BSC testnet',
    chain: 'BSC',
    rpc: [
      'https://data-seed-prebsc-1-s1.bnbchain.org:8545',
      'https://data-seed-prebsc-2-s1.bnbchain.org:8545',
      'https://data-seed-prebsc-1-s2.bnbchain.org:8545',
      'https://data-seed-prebsc-2-s2.bnbchain.org:8545',
      'https://data-seed-prebsc-1-s3.bnbchain.org:8545',
      'https://data-seed-prebsc-2-s3.bnbchain.org:8545',
      'https://bsc-testnet-rpc.publicnode.com',
      'wss://bsc-testnet-rpc.publicnode.com',
    ],
    faucets: ['https://testnet.bnbchain.org/faucet-smart'],
    nativeCurrency: {
      name: 'BNB Chain Native Token',
      symbol: 'tBNB',
      decimals: 18,
    },
    infoURL: 'https://www.bnbchain.org/en',
    shortName: 'bnbt',
    chainId: 97,
    networkId: 97,
    slip44: 1,
    explorers: [
      {
        name: 'bscscan-testnet',
        url: 'https://testnet.bscscan.com',
        standard: 'EIP3091',
      },
    ],
  },
  arbitrumSepoliaTest: {
    name: 'Arbitrum Sepolia',
    pionerChainId: 'arbitrumSepoliaTest',
    config: 'Arbitrum Sepolia',
    title: 'Arbitrum Sepolia Rollup Testnet',
    chain: 'ETH',
    rpc: [
      'https://sepolia-rollup.arbitrum.io/rpc',
      'https://arbitrum-sepolia.infura.io/v3/${INFURA_API_KEY}',
    ],
    faucets: [],
    nativeCurrency: {
      name: 'Sepolia Ether',
      symbol: 'ETH',
      decimals: 18,
    },
    infoURL: 'https://arbitrum.io',
    shortName: 'arb-sep',
    chainId: 421614,
    networkId: 421614,
    slip44: 1,
    explorers: [
      {
        name: 'Arbitrum Sepolia Rollup Testnet Explorer',
        url: 'https://sepolia-explorer.arbitrum.io',
        standard: 'EIP3091',
      },
    ],
    parent: {
      type: 'L2',
      chain: 'eip155-11155111',
      bridges: [
        {
          url: 'https://bridge.arbitrum.io',
        },
      ],
    },
  },
  mumbai: {
    name: 'Mumbai',
    pionerChainId: 'mumbai',
    config: 'Mumbai',
    title: 'Polygon Testnet Mumbai',
    chain: 'Polygon',
    icon: 'polygon',
    rpc: [
      'https://rpc-mumbai.maticvigil.com',
      'https://polygon-mumbai-bor-rpc.publicnode.com',
      'wss://polygon-mumbai-bor-rpc.publicnode.com',
      'https://polygon-mumbai.gateway.tenderly.co',
      'wss://polygon-mumbai.gateway.tenderly.co',
    ],
    faucets: ['https://faucet.polygon.technology/'],
    nativeCurrency: {
      name: 'MATIC',
      symbol: 'MATIC',
      decimals: 18,
    },
    infoURL: 'https://polygon.technology/',
    shortName: 'maticmum',
    chainId: 80001,
    networkId: 80001,
    slip44: 1,
    explorers: [
      {
        name: 'polygonscan',
        url: 'https://mumbai.polygonscan.com',
        standard: 'EIP3091',
      },
    ],
  },
  opSepoliaTest: {
    name: 'OP Sepolia Testnet',
    pionerChainId: 'opSepoliaTest',
    config: 'Optimism Sepolia',
    chain: 'ETH',
    rpc: ['https://sepolia.optimism.io'],
    faucets: ['https://app.optimism.io/faucet'],
    nativeCurrency: {
      name: 'Sepolia Ether',
      symbol: 'ETH',
      decimals: 18,
    },
    infoURL: 'https://optimism.io',
    shortName: 'opsep',
    chainId: 11155420,
    networkId: 11155420,
    slip44: 1,
    explorers: [
      {
        name: 'opscout',
        url: 'https://optimism-sepolia.blockscout.com',
        icon: 'blockscout',
        standard: 'EIP3091',
      },
    ],
  },
  fuji: {
    name: 'Avalanche Fuji Testnet',
    pionerChainId: 'fuji',
    config: 'fuji',
    chain: 'AVAX',
    icon: 'avax',
    rpc: [
      'https://api.avax-test.network/ext/bc/C/rpc',
      'https://avalanche-fuji-c-chain-rpc.publicnode.com',
      'wss://avalanche-fuji-c-chain-rpc.publicnode.com',
    ],
    faucets: ['https://faucet.avax-test.network/'],
    nativeCurrency: {
      name: 'Avalanche',
      symbol: 'AVAX',
      decimals: 18,
    },
    infoURL: 'https://cchain.explorer.avax-test.network',
    shortName: 'Fuji',
    chainId: 43113,
    networkId: 1,
    slip44: 1,
    explorers: [
      {
        name: 'snowtrace',
        url: 'https://testnet.snowtrace.io',
        standard: 'EIP3091',
      },
    ],
  },
  avax: {
    name: 'Avalanche C-Chain',
    pionerChainId: 'avax',
    chain: 'AVAX',
    icon: 'avax',
    rpc: [
      'https://api.avax.network/ext/bc/C/rpc',
      'https://avalanche-c-chain-rpc.publicnode.com',
      'wss://avalanche-c-chain-rpc.publicnode.com',
    ],
    features: [
      {
        name: 'EIP1559',
      },
    ],
    faucets: [],
    nativeCurrency: {
      name: 'Avalanche',
      symbol: 'AVAX',
      decimals: 18,
    },
    infoURL: 'https://www.avax.network/',
    shortName: 'avax',
    chainId: 43114,
    networkId: 43114,
    slip44: 9005,
    explorers: [
      {
        name: 'snowtrace',
        url: 'https://snowtrace.io',
        standard: 'EIP3091',
      },
    ],
  },
  mantaTest: {
    name: 'Manta Pacific Testnet',
    pionerChainId: 'mantaTest',
    config: 'Mantle Testnet',
    chain: 'Manta Pacific',
    rpc: ['https://manta-testnet.calderachain.xyz/http'],
    faucets: [],
    nativeCurrency: {
      name: 'Manta',
      symbol: 'MANTA',
      decimals: 18,
    },
    features: [
      {
        name: 'EIP155',
      },
      {
        name: 'EIP1559',
      },
    ],
    infoURL: 'https://manta-testnet.caldera.dev/',
    shortName: 'mantaTestnet',
    chainId: 3441005,
    networkId: 3441005,
    slip44: 1,
    icon: 'manta',
    explorers: [
      {
        name: 'manta-testnet Explorer',
        url: 'https://manta-testnet.calderaexplorer.xyz',
        standard: 'EIP3091',
      },
    ],
  },
  baseSepoliaTest: {
    name: 'Base Sepolia Testnet',
    pionerChainId: 'baseSepoliaTest',
    config: 'Base Sepolia',
    chain: 'ETH',
    rpc: [
      'https://sepolia.base.org',
      'https://base-sepolia-rpc.publicnode.com',
      'wss://base-sepolia-rpc.publicnode.com',
    ],
    faucets: [],
    nativeCurrency: {
      name: 'Sepolia Ether',
      symbol: 'ETH',
      decimals: 18,
    },
    infoURL: 'https://base.org',
    shortName: 'basesep',
    chainId: 84532,
    networkId: 84532,
    slip44: 1,
    icon: 'baseTestnet',
    explorers: [
      {
        name: 'basescout',
        url: 'https://base-sepolia.blockscout.com',
        icon: 'blockscout',
        standard: 'EIP3091',
      },
    ],
  },
  skevmTest: {
    name: 'Polygon zkEVM Testnet',
    pionerChainId: 'skevmTest',
    config: 'zkEVM Testnet',
    title: 'Polygon zkEVM Testnet',
    chain: 'Polygon',
    rpc: ['https://rpc.public.zkevm-test.net'],
    faucets: [],
    nativeCurrency: {
      name: 'Ether',
      symbol: 'ETH',
      decimals: 18,
    },
    infoURL: 'https://polygon.technology/solutions/polygon-zkevm/',
    shortName: 'testnet-zkEVM-mango',
    chainId: 1442,
    networkId: 1442,
    slip44: 1,
    explorers: [
      {
        name: 'Polygon zkEVM explorer',
        url: 'https://explorer.public.zkevm-test.net',
        standard: 'EIP3091',
      },
    ],
  },
  sonic: {
    name: 'Sonic Testnet',
    pionerChainId: 'sonic',
    rpc: ['https://rpcapi.sonic.fantom.network/'],
    faucets: ['https://app.optimism.io/faucet'],
    chainId: 64165,
    networkId: 64165,
    contracts: {
      FakeUSDAddress: '0x60a75B099Fe78Cb7Fad097bF2C082c467686ecd5',
      PionerV1Address: '0xEA0224877722d59aef9c16aafD83d132634bDaC1',
      PionerV1ComplianceAddress: '0xD6C07Ed68941B2B75c7A42008C446DDf67795ecf',
      PionerV1OpenAddress: '0x4549500cb81DDA59fF8cB21b7b77C630181cDFA5',
      PionerV1CloseAddress: '0x8Fe0bcCAFA648b093C448ed8Bb732F65Cef734c2',
      PionerV1DefaultAddress: '0x91570188747272F90DFF014def0109B399b7d63f',
      PionerV1ViewAddress: '0xc11f825fF2A7Ac7bD4F4B28bDEdbbFA5BaeEC0D9',
      PionerV1OracleAddress: '0xf447AbDcADC871EF6E366f26DBA663bACE45dD5d',
      PionerV1UtilsAddress: '0xb400785d741f8815c657a03eebb04944eb7d7b9c',
      PionerV1WrapperAddress: '0x3941DdF936ffe2de5Cd3648ac5ee2c0F8C171A67',
    },
  },
};
